on: push
name: on push
jobs:
  testsLinux37:
    name: run tests on linux, python3.7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: docker/python:37
      with:
        entrypoint: pip
        args: install .[dev]
